### ISSUE TITLE
React prop interface: missing lint

### ISSUE THREAD

**Issue by BCsabaEngine** [gund/eslint-plugin-deprecation#76] opened 2023-12-14 13:15 UTC
I have tried to use this lint rule for react deprecated props. But it does not work:
```
export type Alpha = {
  /** @deprecated */
  abc: string;
  def: string;
}
const alpha: Alpha = { abc: 'a', def: 'd' }; <-- does not display lint error
alpha.abc = 'b'; <-- display lint error
```

I will try to make a PR for this in the future.

**Comment by gund** [comment] 2023-12-14 19:57
Duplicate of #13

**Closed** 2023-12-14 19:57 UTC
